# Generated by Django 5.2.4 on 2025-07-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_producer_product_slug_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platfrom',
            new_name='Platform',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='platfrom',
            new_name='Platform',
        ),
    ]
