# Generated by Django 5.2.4 on 2025-07-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_rename_platfrom_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Platform',
            new_name='platform',
        ),
    ]
