# Generated by Django 5.2.4 on 2025-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='sklep.genre'),
        ),
    ]
