# Generated by Django 5.2.4 on 2025-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_alter_product_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(to='sklep.genre'),
        ),
    ]
