# Generated by Django 5.2.4 on 2025-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_alter_product_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
