# Generated by Django 5.2.4 on 2025-08-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
