# Generated by Django 5.2.4 on 2025-08-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0012_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
