# Generated by Django 5.2.4 on 2025-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0018_order_email_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'karta kredytowa'), ('paypal', 'PayPal'), ('bank_transfer', 'przelew bankowy'), ('cash_on_delivery', 'płatność przy odbiorze')], max_length=32),
        ),
    ]
